services:
  - type: web
    name: pts-api
    runtime: docker
    plan: free
    dockerfilePath: ./PTS.API/Dockerfile
    dockerContext: ./PTS.API
    dockerCommand: sh -c "dotnet PTS.API.dll --urls http://0.0.0.0:$PORT"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT__KEY
        sync: false
      - key: JWT__ISSUER
        value: PTS.API
      - key: JWT__AUDIENCE
        value: PTS.CLIENT
      - key: ConnectionStrings__DefaultConnection
        sync: false

  - type: web
    name: pts-web
    runtime: static
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/pts-track
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
