// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTS.API.Data;

#nullable disable

namespace PTS.API.Migrations
{
    [DbContext(typeof(PtsDbContext))]
    partial class PtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTS.API.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("integer");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId")
                        .IsUnique();

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubCommit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorGitHub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCommit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepoId")
                        .HasColumnType("integer");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TareaId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("RepoId", "Sha")
                        .IsUnique();

                    b.ToTable("GitHubCommits");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubPR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorGitHub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroPR")
                        .HasColumnType("integer");

                    b.Property<int>("RepoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TareaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("RepoId", "NumeroPR")
                        .IsUnique();

                    b.ToTable("GitHubPRs");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VinculadoPorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId")
                        .IsUnique();

                    b.HasIndex("VinculadoPorId");

                    b.ToTable("GitHubRepos");
                });

            modelBuilder.Entity("PTS.API.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PTS.API.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("PTS.API.Models.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("PTS.API.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("integer");

                    b.Property<int>("CreadaPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<int>("SprintId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("CreadaPorId");

                    b.HasIndex("SprintId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("PTS.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GrupoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PTS.API.Models.Clase", b =>
                {
                    b.HasOne("PTS.API.Models.Usuario", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubCommit", b =>
                {
                    b.HasOne("PTS.API.Models.GitHubRepo", "Repo")
                        .WithMany("Commits")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTS.API.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId");

                    b.Navigation("Repo");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubPR", b =>
                {
                    b.HasOne("PTS.API.Models.GitHubRepo", "Repo")
                        .WithMany("PRs")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTS.API.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId");

                    b.Navigation("Repo");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubRepo", b =>
                {
                    b.HasOne("PTS.API.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTS.API.Models.Usuario", "VinculadoPor")
                        .WithMany()
                        .HasForeignKey("VinculadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("VinculadoPor");
                });

            modelBuilder.Entity("PTS.API.Models.Grupo", b =>
                {
                    b.HasOne("PTS.API.Models.Clase", "Clase")
                        .WithMany("Grupos")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("PTS.API.Models.Proyecto", b =>
                {
                    b.HasOne("PTS.API.Models.Grupo", "Grupo")
                        .WithOne("Proyecto")
                        .HasForeignKey("PTS.API.Models.Proyecto", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PTS.API.Models.Sprint", b =>
                {
                    b.HasOne("PTS.API.Models.Proyecto", "Proyecto")
                        .WithMany("Sprints")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("PTS.API.Models.Tarea", b =>
                {
                    b.HasOne("PTS.API.Models.Usuario", "AsignadoA")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PTS.API.Models.Usuario", "CreadaPor")
                        .WithMany("TareasCreadas")
                        .HasForeignKey("CreadaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTS.API.Models.Sprint", "Sprint")
                        .WithMany("Tareas")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("CreadaPor");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("PTS.API.Models.Usuario", b =>
                {
                    b.HasOne("PTS.API.Models.Grupo", "Grupo")
                        .WithMany("Integrantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PTS.API.Models.Clase", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("PTS.API.Models.GitHubRepo", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("PRs");
                });

            modelBuilder.Entity("PTS.API.Models.Grupo", b =>
                {
                    b.Navigation("Integrantes");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("PTS.API.Models.Proyecto", b =>
                {
                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("PTS.API.Models.Sprint", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PTS.API.Models.Usuario", b =>
                {
                    b.Navigation("TareasAsignadas");

                    b.Navigation("TareasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
